"""initial_schema_audit_logs_and_tokens

Revision ID: fae4016df4b8
Revises: 
Create Date: 2026-02-26 17:26:22.829599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Importar tipo GUID custom para compatibilidad PostgreSQL/SQLite
from app.models.audit_log import GUID


# revision identifiers, used by Alembic.
revision: str = 'fae4016df4b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', GUID(length=36), nullable=False, comment='Identificador único del registro de auditoría'),
    sa.Column('request_id', sa.String(length=50), nullable=False, comment='ID de trazabilidad de la petición (X-Request-ID)'),
    sa.Column('servicio', sa.String(length=50), nullable=False, comment='Nombre del microservicio que genera el evento'),
    sa.Column('endpoint', sa.String(length=200), nullable=False, comment='Ruta del endpoint invocado'),
    sa.Column('metodo', sa.String(length=10), nullable=False, comment='Método HTTP (GET, POST, PUT, DELETE, PATCH)'),
    sa.Column('codigo_respuesta', sa.Integer(), nullable=True, comment='Código de respuesta HTTP'),
    sa.Column('duracion_ms', sa.Integer(), nullable=True, comment='Duración del request en milisegundos'),
    sa.Column('usuario_id', GUID(length=36), nullable=True, comment='UUID del usuario que realizó la acción (puede ser null si es anónimo)'),
    sa.Column('detalle', sa.Text(), nullable=True, comment='Detalle adicional del evento (JSON stringificado, cifrado si es sensible)'),
    sa.Column('ip_origen', sa.String(length=45), nullable=True, comment='Dirección IP de origen del request'),
    sa.Column('timestamp_evento', sa.TIMESTAMP(timezone=True), nullable=False, comment='Momento exacto en que ocurrió el evento en el microservicio origen'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Momento en que se registró en ms-auditoria'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_codigo_servicio', 'audit_logs', ['codigo_respuesta', 'servicio'], unique=False)
    op.create_index(op.f('ix_audit_logs_codigo_respuesta'), 'audit_logs', ['codigo_respuesta'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_servicio'), 'audit_logs', ['servicio'], unique=False)
    op.create_index(op.f('ix_audit_logs_usuario_id'), 'audit_logs', ['usuario_id'], unique=False)
    op.create_index('ix_audit_servicio_timestamp', 'audit_logs', ['servicio', 'timestamp_evento'], unique=False)
    op.create_index('ix_audit_usuario_timestamp', 'audit_logs', ['usuario_id', 'timestamp_evento'], unique=False)
    op.create_table('microservice_tokens',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('nombre_microservicio', sa.String(length=50), nullable=False, comment='Nombre del microservicio (ej: ms-matricula, ms-finanzas)'),
    sa.Column('token_hash', sa.String(length=256), nullable=False, comment='Hash del token de autenticación del microservicio'),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Indica si el microservicio está autorizado para enviar logs'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_microservicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('microservice_tokens')
    op.drop_index('ix_audit_usuario_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_servicio_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_usuario_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_servicio'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_codigo_respuesta'), table_name='audit_logs')
    op.drop_index('ix_audit_codigo_servicio', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
